steps:
  # a pre-build container allows us to build, tag and push docker image
  # Auth service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "me-west1-docker.pkg.dev/sleepr-419018/sleepr/auth:latest",
        "-f",
        "apps/auth/Dockerfile",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "me-west1-docker.pkg.dev/sleepr-419018/sleepr/auth:latest"]
  # Notifications service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "me-west1-docker.pkg.dev/sleepr-419018/sleepr/notifications:latest",
        "-f",
        "apps/notifications/Dockerfile",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "me-west1-docker.pkg.dev/sleepr-419018/sleepr/notifications:latest"]
  # Payments service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "me-west1-docker.pkg.dev/sleepr-419018/sleepr/payments:latest",
        "-f",
        "apps/payments/Dockerfile",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "me-west1-docker.pkg.dev/sleepr-419018/sleepr/payments:latest"]
  # Reservations service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "me-west1-docker.pkg.dev/sleepr-419018/sleepr/reservations:latest",
        "-f",
        "apps/reservations/Dockerfile",
        "."
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "me-west1-docker.pkg.dev/sleepr-419018/sleepr/reservations:latest"]