apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: me-west1-docker.pkg.dev/sleepr-419018/sleepr/auth:latest
        name: auth
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: sleepr
                key: mongoDbConnectionUri
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: sleepr
                key: jwtSecretKey
          - name: JWT_EXPIRATION
            value: "3600"
          - name: HTTP_PORT
            value: "3003"
          - name: TCP_PORT
            value: "3002"
        ports:
          - containerPort: 3002
          - containerPort: 3003